create database QLDA
create table NHANVIEN 
(
MANV CHAR(9) CONSTRAINT PK_NV PRIMARY KEY NOT NULL,
HONV NVARCHAR(15) NOT NULL,
TENLOT NVARCHAR(15),
TENNV NVARCHAR(15) NOT NULL,
NGSINH DATETIME,
DCHI NVARCHAR(50),
PHAI NCHAR(3) NOT NULL,
LUONG FLOAT,
MA_NQL CHAR(9),
PHG INT 
)


create table PHONGBAN
(
TENPHG NVARCHAR(15),
MAPHG INT CONSTRAINT PK_PHONGBAN PRIMARY KEY NOT NULL,
TRPHG CHAR(9) NOT NULL,
NG_NHANCHUC DATETIME
)


create table DIADIEM_PHG
(
MAPHG INT NOT NULL,
DIADIEM NVARCHAR(15) NOT NULL,
PRIMARY KEY (MAPHG, DIADIEM)
)
create table DEAN
(
TENDA NVARCHAR(15),
MADA INT CONSTRAINT PK_DEAN PRIMARY KEY NOT NULL,
DDIEM_DA NVARCHAR(15),
PHONG INT
)
create table CONGVIEC
(
MADA INT NOT NULL,
STT INT NOT NULL,
TEN_CONG_VIEC NVARCHAR(50),
PRIMARY KEY (MADA, STT)
)
create table PHANCONG
(
MA_NVIEN CHAR(9) NOT NULL,
MADA INT NOT NULL,
STT INT NOT NULL,
THOIGIAN DECIMAL(5,1),
PRIMARY KEY (MA_NVIEN, MADA, STT)
)
create table THANNHAN
(
MA_NVIEN CHAR(9) NOT NULL,
TENNV NVARCHAR(15) NOT NULL,
PHAI NVARCHAR(3) ,
NGSINH DATETIME,
QUANHE NVARCHAR(15),
PRIMARY KEY ( MA_NVIEN, TENNV)
)
select * from NHANVIEN
select * from PHONGBAN

/*tao khoa ngoai cho cac bang */
ALTER TABLE NHANVIEN ADD
CONSTRAINT FK_NHANVIEN_PHONGBAN FOREIGN KEY (PHG) REFERENCES PHONGBAN(MAPHG),
CONSTRAINT FK_NHANVIEN_NHANVIEN FOREIGN KEY (MA_NQL) REFERENCES NHANVIEN(MANV)

ALTER TABLE PHONGBAN ADD
CONSTRAINT FK_PHONGBAN FOREIGN KEY (TRPHG) REFERENCES NHANVIEN(MANV)

ALTER TABLE DEAN ADD
CONSTRAINT FK_DEAN FOREIGN KEY (PHONG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE DIADIEM_PHG ADD
CONSTRAINT FK_DIADIEMPHG FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE PHANCONG ADD
CONSTRAINT FK_PHANCONG_CONGVIEC FOREIGN KEY (MADA,STT) REFERENCES CONGVIEC(MADA,STT),
CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY (MA_NVIEN ) REFERENCES NHANVIEN(MANV)

ALTER TABLE CONGVIEC ADD
CONSTRAINT FK_CONGVIEC FOREIGN KEY (MADA) REFERENCES DEAN(MADA)

ALTER TABLE THANNHAN ADD
CONSTRAINT FK_THANNHAN_NHANVIEN FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV)

/*nhap du lieu*/
/*bang nhân viên*/
INSERT INTO NHANVIEN(HONV,TENLOT,TENNV,MANV,NGSINH,DCHI,PHAI,LUONG,MA_NQL,PHG) VALUES
(N'Đinh',N'Bá',N'Tiên','009','02/11/1960',N'119 Cống Quỳnh,TpHCM',N'Nam',30000,NULL,NULL)
INSERT INTO NHANVIEN(HONV,TENLOT,TENNV,MANV,NGSINH,DCHI,PHAI,LUONG,MA_NQL,PHG) VALUES
(N'Nguyễn',N'Thanh',N'Tùng','005','08/20/1962',N'222 Nguyễn Văn Cừ,TpHCM',N'Nam',40000,NULL,NULL)
INSERT INTO NHANVIEN(HONV,TENLOT,TENNV,MANV,NGSINH,DCHI,PHAI,LUONG,MA_NQL,PHG) VALUES
(N'Bùi',N'Ngọc',N'Hưng','007','03/11/1954',N'332 Nguyễn Thái Học,TpHCM',N'Nam',25000,NULL,NULL)
INSERT INTO NHANVIEN(HONV,TENLOT,TENNV,MANV,NGSINH,DCHI,PHAI,LUONG,MA_NQL,PHG) VALUES
(N'Lê',N'Quỳnh',N'Như','001','02/01/1967',N'291 Hồ Văn Huê,TpHCM',N'Nữ',43000,NULL,NULL)
INSERT INTO NHANVIEN(HONV,TENLOT,TENNV,MANV,NGSINH,DCHI,PHAI,LUONG,MA_NQL,PHG) VALUES
(N'Nguyễn',N'Mạnh',N'Hùng','004','03/04/1967',N'95 Bà Rịa, Vũng Tàu',N'Nam',38000,NULL,NULL)
INSERT INTO NHANVIEN(HONV,TENLOT,TENNV,MANV,NGSINH,DCHI,PHAI,LUONG,MA_NQL,PHG) VALUES
(N'Trần',N'Thanh',N'Tâm','003','05/04/1957',N'34 Mai Thị Lự, TpHCM',N'Nam',25000,NULL,NULL)
INSERT INTO NHANVIEN(HONV,TENLOT,TENNV,MANV,NGSINH,DCHI,PHAI,LUONG,MA_NQL,PHG) VALUES
(N'Trần',N'Hồng',N'Quang','008','09/01/1967',N'80 Lê Hồng Phong, TpHCM',N'Nam',25000,NULL,NULL)
INSERT INTO NHANVIEN(HONV,TENLOT,TENNV,MANV,NGSINH,DCHI,PHAI,LUONG,MA_NQL,PHG) VALUES
(N'Phạm',N'Văn',N'Vinh','006','01/01/1965',N'45 Trưng Vương, Hà Nội',N'Nữ',55000,NULL,NULL)
SELECT *
FROM NHANVIEN
/*bang phòng ban*/
INSERT INTO PHONGBAN(TENPHG,MAPHG,TRPHG,NG_NHANCHUC) VALUES
(N'Nghiên cứu',5,'005','05/22/1978')
INSERT INTO PHONGBAN(TENPHG,MAPHG,TRPHG,NG_NHANCHUC) VALUES
(N'Điều hành',4,'008','01/01/1985')
INSERT INTO PHONGBAN(TENPHG,MAPHG,TRPHG,NG_NHANCHUC) VALUES
(N'Quản lý',1,'006','06/19/1971')
SELECT *
FROM PHONGBAN

/*dia diem */
INSERT INTO DIADIEM_PHG(MAPHG,DIADIEM) VALUES
('1',N'TPHCM')
INSERT INTO DIADIEM_PHG(MAPHG,DIADIEM) VALUES
('4',N'HÀ NỘI')
INSERT INTO DIADIEM_PHG(MAPHG,DIADIEM) VALUES
('5',N'TAU')
INSERT INTO DIADIEM_PHG(MAPHG,DIADIEM) VALUES
('5',N'NHA TRANG')
INSERT INTO DIADIEM_PHG(MAPHG,DIADIEM) VALUES
('5',N'TP HCM')
SELECT*
FROM DIADIEM_PHG


/*đề án*/
INSERT INTO DEAN ( TENDA, MADA, DDIEM_DA, PHONG) VALUES 
(N'San pham X','1',N'Vũng Tàu','5')
INSERT INTO DEAN ( TENDA, MADA, DDIEM_DA, PHONG) VALUES 
(N'San pham Y','2',N'Nha Trang','5')
INSERT INTO DEAN ( TENDA, MADA, DDIEM_DA, PHONG) VALUES 
(N'San pham Z','3',N'TP HCM','5')
INSERT INTO DEAN ( TENDA, MADA, DDIEM_DA, PHONG) VALUES 
(N'Tin hoc hoa','10',N'Hà Nội','4')
INSERT INTO DEAN ( TENDA, MADA, DDIEM_DA, PHONG) VALUES 
(N'Cap quang','20',N'TP HCM','1')
INSERT INTO DEAN ( TENDA, MADA, DDIEM_DA, PHONG) VALUES 
(N'Dao tao','30',N'Hà Nội','4')
SELECT *
FROM DEAN
/*bang cong viec*/
INSERT INTO CONGVIEC ( MADA, STT,TEN_CONG_VIEC) VALUES
('1','1',N'Thiet ke san pham X')
INSERT INTO CONGVIEC ( MADA, STT,TEN_CONG_VIEC) VALUES 
('1','2',N'Thu nghiem san pham X')
INSERT INTO CONGVIEC ( MADA, STT,TEN_CONG_VIEC) VALUES 
('2','1',N'San xuat')
INSERT INTO CONGVIEC ( MADA, STT,TEN_CONG_VIEC) VALUES 
('2','2', N'Quang cao san pham Y')
INSERT INTO CONGVIEC ( MADA, STT,TEN_CONG_VIEC) VALUES 
('3','1',N'Khuyen mai san pham Z')
INSERT INTO CONGVIEC ( MADA, STT,TEN_CONG_VIEC) VALUES 
('10','1',N'Tin hoc hoa nhan su tin luong')
INSERT INTO CONGVIEC ( MADA, STT,TEN_CONG_VIEC) VALUES 
('10','2', N'Tin hoc hoa phong Kinh Doanh')
INSERT INTO CONGVIEC ( MADA, STT,TEN_CONG_VIEC) VALUES 
('20','1',N'Lap dat cap quang')
INSERT INTO CONGVIEC ( MADA, STT,TEN_CONG_VIEC) VALUES 
('30','1',N'Triển khai ERP')
SELECT *
FROM CONGVIEC
/*phan cong*/
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('009','1','1','32')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('009','2','2','8')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('004','3','1','40')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('003','1','2','20')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('003','2','1','20')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('008','10','1','35')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('008','30','1','5')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('001','30','1','20')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('001','20','1','15')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('006','20','1','30')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('005','3','1','10')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('005','10','2','10')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('005','20','1','10')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('007','30','1','30')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('007','10','2','10')
---
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('005','1','1','10')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('005','2','1','10')
INSERT INTO PHANCONG(MA_NVIEN,MADA,STT,THOIGIAN) VALUES
('005','30','1','10')

SELECT*
FROM PHANCONG

/*than nhan*/
INSERT INTO THANNHAN(MA_NVIEN,TENNV,PHAI,NGSINH,QUANHE) VALUES	
('005',N'Trinh',N'Nữ','04/05/1976',N'Con gái')
INSERT INTO THANNHAN(MA_NVIEN,TENNV,PHAI,NGSINH,QUANHE) VALUES
('005',N'Khang',N'Nam','10/25/1973',N'Con trai')
INSERT INTO THANNHAN(MA_NVIEN,TENNV,PHAI,NGSINH,QUANHE) VALUES
('005',N'Phương',N'Nữ','02/29/1932',N'Vợ chồng')
INSERT INTO THANNHAN(MA_NVIEN,TENNV,PHAI,NGSINH,QUANHE) VALUES
('001',N'Minh',N'Nam','05/03/1948',N'Vợ chồng')
INSERT INTO THANNHAN(MA_NVIEN,TENNV,PHAI,NGSINH,QUANHE) VALUES
('009',N'Tiến',N'Nam','01/01/1978',N'Con trai')
INSERT INTO THANNHAN(MA_NVIEN,TENNV,PHAI,NGSINH,QUANHE) VALUES
('009',N'Châu',N'Nữ','12/30/1978',N'Con gái')
INSERT INTO THANNHAN(MA_NVIEN,TENNV,PHAI,NGSINH,QUANHE) VALUES
('009',N'Phương',N'Nữ','05/05/1957',N'Vợ chồng')
SELECT*
FROM THANNHAN

UPDATE NHANVIEN
SET MA_NQL='005', PHG=5
WHERE MANV='009'
UPDATE NHANVIEN
SET MA_NQL='006', PHG=5
WHERE MANV='005'
UPDATE NHANVIEN
SET MA_NQL='001', PHG=4
WHERE MANV='007'
UPDATE NHANVIEN
SET MA_NQL='006', PHG=4
WHERE MANV='001'
UPDATE NHANVIEN
SET MA_NQL='005', PHG=5
WHERE MANV='004'
UPDATE NHANVIEN
SET MA_NQL='005', PHG=5
WHERE MANV='003'
UPDATE NHANVIEN
SET MA_NQL='001',  PHG=4
WHERE MANV='008'
UPDATE NHANVIEN
SET PHG=1
WHERE MANV='006'
--Tim nhan vien lam viec o phong so 4
SELECT *
FROM NHANVIEN
WHERE PHG = 4
--Tim NV co luong tren 30000
SELECT *
FROM NHANVIEN N
WHERE N.LUONG>30000
--
SELECT *
FROM NHANVIEN N
WHERE (N.LUONG>25000 AND N.PHG=4) OR (N.LUONG>30000 AND N.PHG=5)
--
SELECT HONV+' '+TENLOT+ ' ' +TENNV AS N'HỌ TÊN NV Ở TPHCM'
FROM NHANVIEN N
WHERE N.DCHI LIKE '% TPHCM'
--
select HONV+ ' ' +TENLOT+ ' ' +TENNV as N'Họ Và Tên' 
from NHANVIEN 
where HONV like 'N%'
--
SELECT n.NGSINH as N'Ngày sinh', N.DCHI AS N'ĐỊA CHỈ'
FROM NHANVIEN N
WHERE N.HONV =N'Đinh' and n.TENLOT= N'Bá' and n.TENNV= N'Tiến'
--
select * from NHANVIEN where year(NGSINH) BETWEEN 1960 AND 1965
--Với mỗi phòng ban, cho biết tên phòng ban và địa điểm phòng
SELECT P.TENPHG, D.DIADIEM
FROM PHONGBAN P, DIADIEM_PHG D
WHERE P.MAPHG=D.MAPHG
--Với mỗi nhân viên, cho biết họ tên của nhân viên đó, họ tên người trưởng phòng và họ tên người quản lý trực tiếp của nhân viên đó.
SELECT N1.HONV+ ' ' +N1.TENLOT+ ' ' +N1.TENNV as N'Họ Và Tên', N2.HONV+ ' ' +N2.TENLOT+ ' ' +N2.TENNV as N'Họ Và Tên NQL', N3.HONV+ ' ' +N3.TENLOT+ ' ' +N3.TENNV as N'Họ Và Tên Trưởng phòng'
FROM NHANVIEN N1, NHANVIEN N2, NHANVIEN N3, PHONGBAN P
WHERE N1.MA_NQL=N2.MANV AND N1.PHG = P.MAPHG AND P.TRPHG=N3.MANV
--Cho biết số lượng đề án của công ty
SELECT COUNT(D.MADA) AS N'SỐ LƯỢNG DA'
FROM DEAN D
--Cho biết số lượng đề án do phòng ‘Nghiên Cứu’ chủ trì
SELECT COUNT(D.MADA)AS N'SỐ LƯỢNG DA CỦA PHÒNG NC'
FROM DEAN D, PHONGBAN P
WHERE D.PHONG=P.MAPHG AND P.TENPHG=N'NGHIÊN CỨU'

--Cho biết lương trung bình của các nữ nhân viên
SELECT AVG(N.LUONG) AS N'LƯƠNG TB CỦA NỮ NV'
FROM NHANVIEN N
WHERE N.PHAI=N'NỮ'
--Với mỗi đề án, liệt kê tên đề án và tổng số giờ làm việc một tuần của tất cả các nhân viên tham dự đề án đó.
SELECT D.TENDA, SUM(P.THOIGIAN) AS N'TỔNG THGIAN LÀM VIỆC'
FROM DEAN D, PHANCONG P
WHERE D.MADA=P.MADA
GROUP BY  P.MADA, D.TENDA
--Với mỗi đề án, cho biết có bao nhiêu nhân viên tham gia đề án đó
SELECT P.MADA, COUNT(P.MA_NVIEN) AS N'SỐ LƯỢNG NV TG'
FROM PHANCONG P
GROUP BY P.MADA
--Với mỗi nhân viên, cho biết họ và tên nhân viên và số lượng thân nhân của nhân viên đó.
SELECT N.HONV+ ' ' +N.TENLOT+ ' ' +N.TENNV as N'Họ Và Tên NV', COUNT(T.TENNV) AS N'SỐ LƯỢNG TN'
FROM NHANVIEN N, THANNHAN T
WHERE N.MANV=T.MA_NVIEN
GROUP  BY T.MA_NVIEN, N.HONV, N.TENLOT, N.TENNV
--Cho biết danh sách các đề án (MADA) có: nhân công với họ (HONV) là ‘Dinh’ hoặc  có người trưởng phòng chủ trì đề án với họ (HONV) là ‘Dinh’.
SELECT D.MADA, D.TENDA
FROM DEAN D, PHANCONG P, NHANVIEN N1
WHERE D.MADA=P.MADA	AND P.MA_NVIEN=N1.MANV AND N1.HONV LIKE N'Đinh'
UNION
SELECT D.MADA, D.TENDA
FROM DEAN D, PHONGBAN P, NHANVIEN N
WHERE D.PHONG=P.MAPHG AND P.TRPHG=N.MANV AND N.HONV LIKE N'ĐINH'

--Danh sách những nhân viên (HONV, TENLOT, TENNV) có trên 2 thân nhân.
SELECT N.HONV+ ' ' +N.TENLOT+ ' ' +N.TENNV as N'Họ Và Tên NV', COUNT(T.TENNV) AS N'SỐ LƯỢNG TN'
FROM NHANVIEN N, THANNHAN T
WHERE N.MANV=T.MA_NVIEN
GROUP  BY T.MA_NVIEN, N.HONV, N.TENLOT, N.TENNV
HAVING COUNT(T.TENNV)>2
--Danh sách những nhân viên (HONV, TENLOT, TENNV) không có thân nhân nào.
SELECT N.HONV, N.TENLOT, N.TENNV
FROM NHANVIEN N
WHERE N.MANV NOT IN (SELECT T.MA_NVIEN
					FROM THANNHAN T)
--Danh sách những nhân viên (HONV, TENLOT, TENNV) làm việc trong mọi đề án của công ty
--R:PHANCONG
--S: DEAN
SELECT DISTINCT R1.MA_NVIEN, N.HONV, N.TENLOT, N.TENNV
FROM PHANCONG R1, NHANVIEN N
WHERE R1.MA_NVIEN=N.MANV AND  NOT EXISTS (SELECT *
					FROM DEAN S
					WHERE NOT EXISTS (SELECT *
										FROM PHANCONG R2
										WHERE R2.MADA=S.MADA AND R2.MA_NVIEN=R1.MA_NVIEN))
--Danh sách những nhân viên (HONV, TENLOT, TENNV) được phân công tất cả đề án do phòng số 4 chủ trì.
--R: PHANCONG
--S: DE AN DO PHONG 4 CHU TRI
SELECT DISTINCT R1.MA_NVIEN, N.HONV, N.TENLOT, N.TENNV
FROM PHANCONG R1, NHANVIEN N
WHERE R1.MA_NVIEN=N.MANV AND  NOT EXISTS (SELECT *
					FROM DEAN S
					WHERE S.PHONG= 4 AND NOT EXISTS (SELECT *
										FROM PHANCONG R2
										WHERE R2.MADA=S.MADA AND R2.MA_NVIEN=R1.MA_NVIEN))


